### PR TITLE
[ExceptionMarshaling] Add.

### PR DESCRIPTION
**Pull request by rolfbjarne**

### CODE REVIEW

**Comment by rolfbjarne** [comment]
@VincentDondain / @olegoid do you usually review samples, or can I just merge this?

**Comment by olegoid** [comment]
@rolfbjarne we usually review samples ;) I'll try to take a look today.

**Comment by conceptdev** [comment]
@olegoid can you ping me too, so i can publish the guide that goes with this sample? thanks!

**Comment by olegoid** [comment]
LGTM 👍

**Pull request merged**
